### ISSUE TITLE
README is missing Spark Logo

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/spark#108]
**Describe the bug**
README.md is not displaying the Spark Logo

**To Reproduce**
1. Go to https://github.com/inland-empire-software-development/spark
2. Scroll down to README

**Expected behavior**
Show the spark logo

**Screenshots**
![image](https://user-images.githubusercontent.com/36907562/75703810-0eefab00-5c6d-11ea-9fdc-1f1d835d7f18.png)

![image](https://user-images.githubusercontent.com/36907562/75703826-1adb6d00-5c6d-11ea-8553-a1f1d4afa466.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] : I don't know

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] : Samsung Galaxy 6
 - OS: [e.g. iOS8.1] : Android
 - Browser [e.g. stock browser, safari] : Chrome
 - Version [e.g. 22] : I don't know

**Comment by lloan** [comment]
@RA1990  is this something you can tackle? Thanks!

**Comment by RA1990** [comment]
on it

**Comment by lloan** [comment]
Thanks, @RA1990 - assigning the task to you - thanks!

**Comment by lloan** [comment]
Thanks @RA1990 looks like this has been merged.
