### ISSUE TITLE
Jenkins failing to build due to error in db.ts

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/spark#140]
**Describe the bug**
For SparkDEV and SparkPRD, Jenkins is failing to build because 'fsyncSync' is declared but its
value is never used.

**To Reproduce**
1. Go to the IESD Jenkins dashboard
2. Click on 'iesd spark DEV' in the list of applications
3. On the left side click 'Build Now'
4. Under build history on the left side click on the # that represents the current running build
5. Click on console output on the left side and the error should be there.

Alternatively you can also look at the old build histories too if you don't want to run the build.

**Expected behavior**
Build should be successful and site should be up 

**Screenshots**
![image](https://user-images.githubusercontent.com/36907562/82924103-b7da3900-9f30-11ea-8f9d-a4c99857bfe0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: latest

**Additional context**
Can be seen on pm2 that both PRD and DEV is down

**Comment by Andymendez100** [comment]
I see the variable got push in with this pull request. User info input #129 
I will implement a fix and update code. Thanks @tonynguyen111997

**Comment by dhuan008** [comment]
@Andymendez100 That's my pr, I think I pulled from uncompleted components my component interacts with. Let me know if I can help.
