### ISSUE TITLE
Record every time a user logs in to their accounts (last_login)

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#24]

**Comment by JacobSNGoodwin** [comment]
@lloan and @Andymendez100m, do I need to create an updateUser method on db in lib/db.ts? I don't think it exists yet. Maybe it's somewhere else. 

... just wrapping my head around the architecture. As I understand it, the endpoints in pages/api are calling the actual db methods in lib/db.ts.

**Comment by JacobSNGoodwin** [comment]
Any thoughts on the flow of this? Any ways you've seen this done before?

Right now when logging in, we're getting the user and checking their password. Would the most sensible thing to do be to update the user table after this has all been completed successfully? It would require multiple SQL queries, but it would be certain we have a valid login before updating the table.

I know there is also a way to get a column with a timestamp to update automatically on an update. But I would suppose that we'd want to check the password first and this way of doing things would keep us from being sure the password was correct.

I have also seen examples of keeping a separate table for all logins.

**Comment by lloan** [comment]
Left a note on #113 - I think we can approach it the way you suggested. I can't imagine we will ever have 1000 users. Obviously, this wouldn't scale, but for v1 it should be fine. We can worry about optimization for v2.

**Comment by lloan** [comment]
Personally tested and this works on dev at the moment. Thanks, @JacobSNGoodwin !
