### ISSUE TITLE
Update the documentation to reflect project

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#31]
Components that require updating:
- README.md file 

Tech to be used:
- Markdown     

What is the current behavior:
The current readme file has the information for the next-authenticate project. 

What is the new behavior:
The readme should talk about what the Spark LMS is or at least the purpose. We can have all the required sections, such as getting started, technology this is built with, members working (authors) on this [Spark team members], links to the assets or resources, etc. At the very minimum, let's add the Spark logo and update the description.

**Comment by RA1990** [comment]
I pick this one up

**Comment by lloan** [comment]
@RA1990 You can use this url for the spark logo: https://raw.githubusercontent.com/inland-empire-software-development/spark/staging/public/images/spark.png 

Just keep in mind that I'm going to be uploading the logos as they're supposed to be used, based on the brand guidelines I provided earlier this week. 

I merged #35 - the PR - you can go and take a look.

Take a look at the main repository for IESD's website - try centering the new logo, when we upload it. Stylize it a bit, think of this as the first impression your work will have on users when they see this repo. Make sure that we take out as much as we can about next-authenticate from the documentation, it could be listed as part of the tech used, but the documentation will be about Spark as an LMS. And make sure to update the list of authors - make sure to include your name.

**Comment by RA1990** [comment]
you got it

**Comment by RA1990** [comment]
How does this sound for the copy for spark?

Spark is a nonprofit dedicated to growing the tech community in the Inland Empire. Our work involves helping community members gain the skills and tools necessary to find employment in the local tech industry.This is accomplished by utilizing a Learning management system. A learning management system (LMS) is a software application for the administration, documentation, tracking, reporting, and delivery of educational courses, training programs, or learning and development programs. The learning management system concept emerged directly from e-Learning. In pursuit of our mission, we strive to foster a climate of purposeful inclusion where members can feel safe, valued and given an opportunity to form meaningful connections with each other. To improve communities through free technical training and opportunities to gain experience through collaboration, networking and knowledge sharing.

**Comment by lloan** [comment]
#83 finalizes this - pushed to master - dev & stg are updated.
