### ISSUE TITLE
Creation of dev, stg and prd tier databases for application.

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#32]
**Components that require updating:**
- Server services

**Tech to be used:**
- MySQL
- Ubuntu
- Shell 

**What is the current behavior:**
We currently have a remote DB for our project, where local work and development work will be using. 

**What is the new behavior:**
We need to create multiple tiers of the database. 
- [x] Development tier -> spark_dev_db
- [x] Create user for dev DB
- [x] Staging tier -> spark_stg_db
- [x] Create user for stg DB
- [x] Production tier -> spark_prd_db
- [x] Create user for prd DB

For each tier, you need to create a specific user that will be used by the application and a different password that is safe - use a secure password generator. 

**Justification:** We need to be able to test features in the future, on different tiers, without worrying about ruining data integrity. Having multiple tiers will help us save time.

**Notes:** This will not impede initial development of project or current development. But will require an additional task to be created to incorporate the dynamic aspect of loading the appropriate tier based on the host. Initial idea is to set these items within .env file and use logic in db file to use host url to know which DB information to use.

**Comment by lloan** [comment]
@Andymendez100 this is ready to pick up, it has been assigned to you. Once you are ready, let me know and I'll send you access to the mySQL server.

**Comment by Andymendez100** [comment]
I have created the db's and users. I have not set any privileges to any of the users. Let me know if anything else is needed @lloan

**Comment by lloan** [comment]
@Andymendez100 make sure that each DB has its own user and password. Each DB user should have access to only that specific DB.

**Comment by Andymendez100** [comment]
@lloan that has already been done as well.

**Comment by lloan** [comment]
@Andymendez100 great job - thanks! Verified that it works.
