### ISSUE TITLE
Add support for new tier domains via nginx with SSL certificates

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#33]
**Components that require updating:**
- Server 

**Tech to be used:** 
- Nginx
- SSL
- Certbot
- Shell

**What is the current behavior:**
We currently don't have sub-domain names.

**What is the new behavior:**
We need to add support for newly added sub-domains (in DNS host) via Nginx and install SSL certificate for each tier. 

- PRD tier will be spark.iesd.com - port 6001
- STG tier will be spark-stg.iesd.com - port 6002
- DEV tier will be spark-dev.iesd.com - port 6002

- [x] Add nginx configuration files for each new domain
- [x] Refresh nginx service and test 
- [x] Add SSL cert to all new domains using certbot 
- [x] Refresh nginx service and test 
- [x] confirm all domains are working fine after propagation.

**Justification:** We need to be able to identify each tier with a user friendly URL.

**Notes:** This will not impede initial development of project or current development.

**Comment by Andymendez100** [comment]
Everything in the checklist has been done. Please tell me if anything else needs to be done associated with this issue. 😄 @lloan

**Comment by lloan** [comment]
Looks good - thanks!
