### ISSUE TITLE
Setup sub-domains for dev, stg and prd tiers for application

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#34]
**Components that require updating:**
- DNS Host

**Tech to be used:**
- DNS management 

**What is the current behavior:**
We currently don't have sub-domain names.

**What is the new behavior:**
We need to setup the sub-domains via management host tool. 
- [ ] Add sub-domains via DNS Management tool (dev, stg, prd) 
- PRD tier will be spark.iesd.com
- STG tier will be spark-stg.iesd.com
- DEV tier will be spark-dev.iesd.com 

**Justification:** We need to be able to identify each tier with a user friendly URL.

**Notes:** This will not impede initial development of project or current development.

**Comment by Andymendez100** [comment]
@lloan @tonynguyen111997 Per conversation with Tony. This has been completed already.

**Comment by lloan** [comment]
Thanks for testing - much appreciated!
