### ISSUE TITLE
Design navigation component

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#36]
**Components that require updating:**
- Navigation

**Tech to be used:**  
- Design tools 

**What is the current behavior:**
We currently don't have a navigation component.

**What is the new behavior:**
Create a design PDF and for developers to convert it to code. You will be using UIKit components along with Fontawesome PRO icons. Any comments you need to make, make them in the discussion of the issue or the implementation issue for this component. 

The expected deliverable will be a component that is shows the possible states it has. Provide notes as necessary. 

**Justification:** Vital component

**Comment by hotRedPanda1** [comment]
There should be a link to the ABOUT page. 
There should be a link to a HELP page. 
There should be a HOME tab
There should be  BACK & FORWARD  buttons.

**Comment by lloan** [comment]
@hotRedPanda1 great input, I will make sure to add this where possible within the design once its revised this week.

**Comment by hotRedPanda1** [comment]
@lloan 
Thank you!

**Comment by lloan** [comment]
@hotRedPanda1 as of now, the about content will be under the `cohorts` item in the navigation. The `help` item will be on the sidebar within the dashboard to provide help for students. The `home` item has been added. And the back and forth between pages will be done by a component called the `breadcrumb` component.

**Comment by lloan** [comment]
Overall design: 
![navigation-bar](https://user-images.githubusercontent.com/3924990/72645939-b452f780-3929-11ea-9f28-6ba8d1559c40.jpg)

Will be posting all assets in #38 - closing this one and marking as complete.

**Comment by hotRedPanda1** [comment]
Why is there a cohorts button?  We are trying to make things less confusing
for the user, not cool and convoluted.

**Comment by lloan** [comment]
The top navigation is omnipresent - there for the front-end and the backend (dashboard) - so it's going to have a link to go home, a link to read about the cohorts we lead (groups of people) - this would display the different cohorts we do, blog will go back to www.iesd.com's blog in the interim and contact would lead to a page with contact information and different avenues to inform the user about our learning program. 

Again, this is NOT the only navigation component. The other one will be the sidebar, for when the user signs in and is authenticated. 

Do you have a suggestion for replacing `Cohorts`?

**Comment by hotRedPanda1** [comment]
No, I just needed to know its relevance and if there were a simpler
expression that stated the same thing (a synonym) that would not sound so
foriegn or scary to new comers.

**Comment by lloan** [comment]
Navigation notes: 
![navigation-bar-notes](https://user-images.githubusercontent.com/3924990/72742534-ca95c900-3b5e-11ea-9708-83e740db0538.jpg)

**Comment by lloan** [comment]
Navigation - Active state: 

PDF: [navigation-revision.pdf](https://github.com/inland-empire-software-development/spark/files/4087089/navigation-revision.pdf)

JPGs:
![navigation-revision](https://user-images.githubusercontent.com/3924990/72742879-7b9c6380-3b5f-11ea-8290-5764e86f7c11.jpg)
![navigation-revision-notes](https://user-images.githubusercontent.com/3924990/72742880-7c34fa00-3b5f-11ea-94d4-11f39addfda4.jpg)

**Comment by lloan** [comment]
To include the help button request from #45 : 

![navigation-revision-v2](https://user-images.githubusercontent.com/3924990/72743574-cbc7f580-3b60-11ea-81c4-21a0f42234d2.jpg)
![navigation-revision-v2-notes](https://user-images.githubusercontent.com/3924990/72743577-cbc7f580-3b60-11ea-92a1-c00e75cff287.jpg)
