### ISSUE TITLE
Create Jenkins jobs for all tiers - deployment trigger.

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#44]
**Components that require updating:**
- Jenkins

**Tech to be used:** 
- Jenkins
- Shell
- GitHub

**What is the current behavior:** We don't have any Jenkins jobs for this project. 
 
**What is the new behavior:** We need a job for each tier: PRD, STG and DEV. These jobs need to update the VM with the new files from the repository after resetting the respective directory and then rebuild. 
  
**Justification:**  CI value 
 
**Notes:** Sample of another job we have...

```
cd /xx/xxx/xxxx/xxxxx/;
whoami;
sudo git reset --hard;
sudo rm -rf yarn.lock;
sudo git fetch;
sudo git pull -f;
sudo yarn install;
sudo yarn build;
sudo pm2 delete iesdstg;
sudo pm2 start yarn --name iesdstg -- staging;
```

This requires that you make sure we have yarn installed, pm2 installed and proper permissions set for Jenkins.

**Comment by RA1990** [comment]
I'll take this one

**Comment by lloan** [comment]
So I think @Andymendez100 wants to take this one so he can learn how to work with Jenkins. Did you have experience with Jenkins or wanted to learn how to work with Jenkins, cause if so, I could get on a call with both of you and we could do one together and then you could each set up a job by yourselves.

**Comment by RA1990** [comment]
Yea that sounds great. I don't have any experience with Jenkins

**Comment by Andymendez100** [comment]
We have to make sure we have a script in package.json called staging, production, and development to start the nextjs job

**Comment by Andymendez100** [comment]
The jenkins jobs have been created and only need to be added a script in the package.json to trigger. @lloan

**Comment by lloan** [comment]
Will mark this complete once we move www.iesd.com to the performance + tier and verify that this works @Andymendez100

**Comment by lloan** [comment]
All jobs created - 

spark.iesd.com - prd branch 
spark-stg.iesd.com - stg branch 
spark-dev.iesd.com - dev branch
