### ISSUE TITLE
[wip] Create HELP Button

### ISSUE THREAD

**Issue by hotRedPanda1** [inland-empire-software-development/spark#45]
**Is your feature request related to a problem? Please describe.**
There should be a HELP button on the site somewhere.

**Describe the solution you'd like**
The must be a substantial FAQ to match query to before it gets turned over to support crew. 
There must be a prompt response (1 to 3 days) to all non-FAQ queries. 

**Describe alternatives you've considered**
//WIP//

**Additional context**
Will require a universal symbol (?) . 
Must be visible. 
May have chat capability.

**Comment by lloan** [comment]
Addressed in #36
