### ISSUE TITLE
//WIP// User Profile Dropdown

### ISSUE THREAD

**Issue by hotRedPanda1** [inland-empire-software-development/spark#47]
**Is your feature request related to a problem? Please describe.*
I do not like when I have to hunt to find out where to edit my profile. It should be in a drop down under the user's profile picture/avatar.

**Describe the solution you'd like**
When the user clicks on the dropdown button near their user profile picture, PROFILE should be one of the offered buttons.
When the Profile button is clicked, the user should see an EDIT button. 

**Describe alternatives you've considered**
In the side menu there should be a second link to the PROFILE button, 

**Additional context**

**Comment by lloan** [comment]
Featured request addressed in #37 

![image](https://user-images.githubusercontent.com/3924990/72704332-5252e780-3b0d-11ea-93ef-e8c992bdc86d.png)
