### ISSUE TITLE
Move www.iesd.com to performance + server

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#54]
**Components that require updating:**
- Jenkins

**Tech to be used:** 
- Jenkins
- Shell
- GitHub

**What is the current behavior:** We don't have any Jenkins jobs for the www.iesd.com site on the new performance + server. 
 
**What is the new behavior:** We need a job for each tier: PRD, STG and DEV. These jobs need to update the VM with the new files from the repository after resetting the respective directory and then rebuild. 
  
**Justification:**  CI value 
 
**Notes:** Sample of another job we have...

```
cd /xx/xxx/xxxx/xxxxx/;
whoami;
sudo git reset --hard;
sudo rm -rf yarn.lock;
sudo git fetch;
sudo git pull -f;
sudo yarn install;
sudo yarn build;
sudo pm2 delete iesdstg;
sudo pm2 start yarn --name iesdstg -- staging;
```

This requires that you make sure we have yarn installed, pm2 installed and proper permissions set for Jenkins. 

The jobs might already be up on Jenkins from when we transferred data to p+ servers.

We need to add support for newly added sub-domains (in DNS host) via Nginx and install SSL certificate for each tier. 

This will most likely require you to update the repository (all 3 branches) to reflect the correct ports within the `package.json` file. 
- PRD tier will be iesd.com - port 6004
- STG tier will be stg.iesd.com - port 6005
- DEV tier will be dev.iesd.com - port 6006

- [x] Add nginx configuration files for each new domain
- [x] Refresh nginx service and test 
- [x] Point A record to new server.
- [x] Add SSL cert to all new domains using certbot (think it only works after DNS has propagated)
- [x] Refresh nginx service and test 
- [x] confirm all domains are working fine after propagation.

**Comment by lloan** [comment]
This can wait. Just realized we're pointing the A records to the new server in the meantime. We can transfer the api.iesd.com site first - that will require moving the WordPress instance as we depend on it as an API.

**Comment by tonynguyen111997** [comment]
dev.iesd.com, staging.iesd.com and iesd.com are now on the new p+ server. I'm going to move this issue into testing.

**Comment by tonynguyen111997** [comment]
@Andymendez100 @dhuan008 Can you please check to make sure everything is working?

**Comment by tonynguyen111997** [comment]
**Steps taken to migrate iesd.com to p+ server**

1. su - jenkins
2. navigate to where the project folder will be
3. Clone repo
4. Give jenkins permission of files (sudo chown jenkins:jenkins -R ./folder_name)
5. cd into folder
6. sudo yarn install
7. sudo yarn build (If it's a NEXT application)
7.  sudo pm2 start "sudo yarn script_name" --name pm2_service_name
8. cd /etc/nginx/conf.d
9. touch domain.name.com.conf
10. Paste below into domain.name.com.conf:
```
server {
    server_name DOMAIN_NAME_HERE;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        proxy_pass http://IP_ADDRESS:PORT_NUMBER/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }

}
```

11. sudo systemctl restart nginx
12. Point A record to new server.
13. sudo certbot -d subdomain.iesd.com
14. Choose "Redirect" option when prompted by cerbot
15. sudo systemctl restart nginx
