### ISSUE TITLE
Add support for Storybook.js 

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#62]
@RA1990 you can upload your screenshots here. 

We will be using storybook to self document our components, keep track of the states of components and prevent regressions.

**Comment by RA1990** [comment]
PR https://github.com/inland-empire-software-development/spark/pull/66

**Comment by lloan** [comment]
support for storybook has been added with `storybook-config` branch - @RA1990  can you test it out. Finishing the refactoring of the last few remaining components.

**Comment by lloan** [comment]
Support for storybook has been added. You can check dev branch.
