### ISSUE TITLE
New course_meta, course tables for course information 

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#70]
We need two tables created.
- [ ] course_meta
- [ ] course 

These tables will be used to provide data on courses. Fields required will be provided by rest of the team.

**Comment by lloan** [comment]
@RA1990 can you provide a list of preliminary fields that you see we need, based on he image.

**Comment by RA1990** [comment]
yes I can I think maybe no yes I can

**Comment by RA1990** [comment]
fields required
- [ ] Course instructor
- [ ] If User is Enrolled
- [ ] if User Cancelled
- [ ] Image
- [ ] Course description
- [ ] Users
- [ ] Users Comments
- [ ] Course star ranking

**Comment by lloan** [comment]
This is complete and can be found in the local spark database.
