### ISSUE TITLE
SignUp component requires CSS tweak

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/spark#72]
**Describe the bug**
Sign up form needs to be tightened up and tested to work on mobile. 

**To Reproduce**
1. Go to 'localhost:3000/authenticate'
2. Click on the signup tab

**Expected behavior**
The signup component should not bounce when viewing the password. Users should be able to click on show/hide password without the bottom element hiding half of the clicking area. Make sure to view gif below - if you find any other issues, denote them in your PR for this issue. 

**Screenshots** 
![signup-form](https://user-images.githubusercontent.com/3924990/75642903-fe4e1f00-5bf1-11ea-883f-770665983701.gif)

**Comment by VelazquezLuis** [comment]
fixed done @lloan

**Comment by zootechdrum** [comment]
Is this issue still open. It looks like @VelazquezLuis fixed it.

**Comment by lloan** [comment]
Great job @VelazquezLuis!

Thanks for following up @zootechdrum
