### ISSUE TITLE
Login button at index page doesn't route to /authenticate

### ISSUE THREAD

**Issue by Maxbrain0** [inland-empire-software-development/spark#94]
**Describe the bug**
The Login button from the home page makes no redirection.

**To Reproduce**
1. run
`yarn dev`
2. Open localhost:3000 in the browser.
3. Click the "Login" button in the center of the page

You are  not sent to  localhost:3000/authenticate

**Expected behavior**
You are sent to loc

**Screenshots**

**Desktop (please complete the following information):**
Using OS X in Firefox and Chrome

**Smartphone (please complete the following information):**

**Additional context**
This worked before the button was updated. Will see if I can fix it.

**Comment by Maxbrain0** [comment]
Looking at it, I don't think setting the href property on the button does anything as there is no anchor tag. All other uses of button use the callback property to set the new url, though I'm not really sure what the button wrapper Component is doing for us. I feel like you can use jsx listeners and UI-kit classnames to get the effect you want. But maybe it enforces some standard button types for the application.

**Comment by lloan** [comment]
The button component needs to be cleaned up a bit. It should no longer be used for linking to things - that's what anchor tags are for and if they're internal links, we can use the `<Link` component. Right now, the main purpose for the buttons are to submit forms or data (actions) - we can add styling to anchors to look like buttons if we want, but they wouldn't need any further logic, so we wouldn't need a component for them.

**Comment by lloan** [comment]
Button component was removed - we will no longer use it, we will use UIKit styling out of the box with minor customizations as needed. Links (that go elsewhere and don't provide side effects [not actions]) will be used for anchor tags `<Link>` as this provides the routing capability that is out of the box with next.js.
